#!/bin/sh
exec java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.desktop/sun.awt=ALL-UNNAMED -Dlogback.configurationFile=$PWD/log-debug.xml -jar ./build/libs/osrs-environment-exporter-fat-2.0.2.jar "$@"
